version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    restart: always
    volumes:
      - ./:/src/app
      - /src/app/node_modules
    command: sh -c 'npm run db:sync && npm run start:dev'
    env_file:
      - './docker-secrets/api.env'
    ports:
      - 3000:3000
      - 80:8080
    depends_on:
      - postgres-db
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    env_file:
      - './docker-secrets/pgadmin.env'
    ports:
      - 8080:80
    volumes: 
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on: 
      - postgres-db
  postgres-db:
    image: 'postgres'
    restart: always
    env_file:
      - './docker-secrets/postgres-db.env'
    container_name: postgres-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data