version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/src/app
      - ./src/app/node_modules
    command: npm run start:dev
    environment:
      - PORT=3000
    ports:
      - 3000:3000
      - 8080:8080